### ISSUE TITLE
Unicode Problem

### ISSUE THREAD

**Issue by Nisutec** [jaraco/configparser#38]
Why are special charakters are not supportet yet ?

`placeholder : 🢂`
`placeholder : ➲ `

The output is ðŸ¢ from `placeholder : 🢂`. How i can fix it

When i change 🢂 to \U0001F882 the result is:

```
print('🢂')
test = '\U0001F882'
print(type(test))
print(test)
test2 = config.get('Hurra!!!', 'placeholder')
print(type(test2))
print(test2)
```
Output is:
```
🢂
<class 'str'>
🢂
<class 'str'>
\U0001F882
```

**Comment by jaraco** [comment]
First off, if you're using Python 3, which it looks like you are, then you're probably not using this project (the backport), but you're probably using the version from the standard library. So the better place to report this issue is probably upstream at https://bugs.python.org.

But before you do that, it might be better to ensure that the behavior you've encountered is in fact a bug. I suggest first posting to StackOverflow (or another support forum) to get more help ensuring your usage is correct.

To get better help, you should report (a) what your environment is, such as operating system, python version, and (if appropriate) the configparser backport version, and (b) what you expected to happen, what actually happened (you did this), and what steps you or someone else could run to replicate the issue.

I tried replicating your issue, but was unsuccessful. On Python 3.7.3 on macOS:

```
>>> strm = open('sample.ini', 'w')
>>> print('[section]', file=strm)
>>> print('placeholder=\U0001F882', file=strm)
>>> strm.close()
>>> import configparser
>>> config = configparser.ConfigParser()
>>> config.read('sample.ini')
['sample.ini']
>>> config.get('section', 'placeholder')
'🢂'
>>> ord(config.get('section', 'placeholder'))
129154
>>> hex(129154)
'0x1f882'
```

As you can see, the built-in configparser on Python 3.7.3 reads the unicode character just fine from the file.

It may be that you're having issues printing the character in your terminal. The first thing I'd do is perform some tests on the value inside of Python as I've done above (such as looking at the 'ord' of the character).

I wish you luck.
