### ISSUE TITLE
configparser doesn't install with older versions of setuptools

### ISSUE THREAD

**Issue by idgserpro** [jaraco/configparser#39]
### Steps to reproduce
```shell
mkdir test
cd test
virtualenv --no-setuptools py
wget https://github.com/buildout/buildout/blob/master/bootstrap/bootstrap.py
# Add file buildout.cfg
py/bin/python bootstrap.py
bin/buildout
```
Where:
buildout.cfg
```
[buildout]

parts = configparser

index = https://pypi.org/simple/

versions = versions

[configparser]
recipe = zc.recipe.egg
eggs=configparser

[versions]
setuptools=26.1.1
zc.buildout=1.7.1
```
Then I get the error:

```
Getting distribution for 'zc.buildout==1.7.1'.
Got zc.buildout 1.7.1.
Getting distribution for 'setuptools==26.1.1'.
warning: no files found matching '*' under directory 'setuptools/_vendor'
Got setuptools 26.1.1.
Upgraded:
  zc.buildout version 1.7.1,
  setuptools version 26.1.1;
restarting.
Generated script '/tmp/test/bin/buildout'.
/home/user/.buildout/eggs/setuptools-26.1.1-py2.7.egg/pkg_resources/__init__.py:188: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
  stacklevel=1,
Getting distribution for 'zc.recipe.egg<2dev'.
Got zc.recipe.egg 1.3.2.
Installing configparser.
Getting distribution for 'configparser'.
zip_safe flag not set; analyzing archive contents...
backports.__init__: module references __path__
Installing configparser 3.7.4
Caused installation of a distribution:
UNKNOWN 0.0.0
with a different project name.
Installing configparser 3.7.4
Caused installation of a distribution:
UNKNOWN 0.0.0
with a different version.
Got None.
Getting distribution for 'configparser'.
zip_safe flag not set; analyzing archive contents...
backports.__init__: module references __path__
Installing configparser 3.7.4
Caused installation of a distribution:
UNKNOWN 0.0.0
with a different project name.
Installing configparser 3.7.4
Caused installation of a distribution:
UNKNOWN 0.0.0
with a different version.
Got None.
While:
  Installing configparser.
Error: There is a version conflict.
We already have: UNKNOWN 0.0.0
```

**Comment by jaraco** [comment]
With later versions of configparser, I switched the package to use declarative config, which requires Setuptools 30.4. The current master of configparser declares a requirement of setuptools 40.7 (although I suspect you'll get a satisfactory build with setuptools 30.4 or later). If you must have an old version of setuptools and build from source, I would also recommend using an old version of configparser.

I do see that the changelog doesn't make explicit mention of this change, so I definitely should add some note about that change, which happened in the 3.7 release, so 3.5.x should still be viable on these older setuptools versions. Will that address your issue?

**Comment by idgserpro** [comment]
@jaraco is it possible to have an install_requeres:

```setuptools = >= 30.4```

Or is setuptools not a dependency?

**Comment by jaraco** [comment]
Setuptools is a "build dependency". It's required to build the package, but not needed at runtime (what "install_requires" specifies). The build dependency [is specified in the pyproject.toml](https://github.com/jaraco/configparser/blob/4ea7a3437ab84eefdb363b0de35cd0d3034fd5ff/pyproject.toml#L2), although it's only honored by tools that support [PEP 518](https://www.python.org/dev/peps/pep-0518/) (namely pip).

In the old days, "setup_requires" was intended as a means to indicate build dependencies, but it could never have been used to specify a setuptools version because it was a setuptools feature and setuptools was already imported/running by the time setup_requires was processed.

It's conceivable that buildout could grow PEP 517/518 support, in which case it would be able to build a wheel of configparser, honoring the pyproject.toml build requirements, and then install that wheel. That's probably no small task, though the [pep517 project](https://github.com/pypa/pep517) might provide most of the facilities for doing that.

Unfortunately, I'm not aware of any other way in buildout/setuptools to enforce a build-time dependency on a particular setuptools version, so the best I can offer is for installers to refer to the pyproject.toml and try to keep up with those versions (or pin to older configparsers that have less strict requirements).

**Comment by idgserpro** [comment]
@jaraco maybe a note in the README about this is good. Changes tend to grow and the note gets lost.

**Comment by jaraco** [comment]
I'm a little reluctant to duplicate the structured requirements specifications from pyproject.toml in an unstructured README for a couple of reasons. First, it requires the project to maintain the value in two separate places or they get out of sync. Second, if I do that for this project, does that not imply I should do it also for every other project?

In other words, I don't think this project (or any other) should be documenting how packaging works.

What I wouldn't be opposed to is something like a badge, something like "built on PyPA", which links to documentation about packaging, where users could educate themselves on how the system is meant to work - what files to look at to understand the build requirements or install requirements, how to build the project, etc. I'd be happy to include that and apply it to all of the projects that I maintain.

To do that, someone would have to create that badge and might also want to provide a nice landing page (if [the home page for the packaging user's guide](https://packaging.python.org/) isn't suitable).
