### ISSUE TITLE
ConfigParser allow_no_value option doesn't work

### ISSUE THREAD

**Issue by nikolaystanishev** [jaraco/configparser#41]
Hello,

I try to read dictionary with None value from ConfigParser and I am expecting to have None value in config_parser object but instead of None I have empty string.

```python
from configparser import ConfigParser
config_parser = ConfigParser(allow_no_value=True)
a = {'a': {'b': None}}
config_parser.read_dict(a)

config_parser.items('a')  # [('b', '')]
```

I try to play with ConfigParser and find out that this problem is coming from:
```python
_DEFAULT_INTERPOLATION = BasicInterpolation()
```
which I also need. If I change default interpolation to:
```python
_DEFAULT_INTERPOLATION = Interpolation()
```
I don't have problem with None values but I have problems with interpolation.

**Comment by jaraco** [comment]
Hi Nikolay. This project is the backport of the CPython configparser from the Python 3.x standard library. If your issue is specifically with the backport, then we can address those here. I suspect, however, that your issue is with the canonical implementation in Python.

I'd probably start by asking your question at https://discuss.python.org/c/users.

When you do, they'll probably want you to answer these questions: Why do you expect `None` for `a.b`? What are the problems you have with `Interpolation`? Do you have similar problems when reading values from a file [I'm not personally familiar with the use of `read_dict`]?

Good luck, and feel free to respond here or file a new ticket if you encounter an issue with the backport.
