### ISSUE TITLE
Request to handle file not found error

### ISSUE THREAD

**Issue by rogerganga** [jaraco/configparser#53]
The library does currently does not handle File Not Found Error.

**Scenario:**

Consider a situation where config/test.ini is not created yet.

`config = configparser.ConfigParser()
config.read("config/test.ini")
key = config['db']['key']`

**Expected Response:** 
`File not found error: The file test.ini is not found`

**Actual Response:**
`Key Error: 'db'`

**Comment by Vickygum** [comment]
I am also facing this error, Please fix this

**Comment by jugmac00** [comment]
Quote from the docstring of ConfigParser (the one from cpython):
>  Files that cannot be opened are silently ignored; this is
designed so that you can specify an iterable of potential
configuration file locations (e.g. current directory, user's
home directory, systemwide directory), and all existing
configuration files in the iterable will be read.

https://github.com/jugmac00/cpython/blob/610a60c601fb4380eee30e15be1cd4dcbdaeec4c/Lib/configparser.py#L679-L687

So this is working as intended.

**Comment by jaraco** [comment]
Thanks for finding that, jugmac. That's right. This project is a backport. If you wish to alter the behavior, you'll want to file a bug with the upstream CPython project, but be prepared to provide a strong rationale why the change is worth the effort.
