### ISSUE TITLE
Request for Feature: Addition of Function to Return Dictionary

### ISSUE THREAD

**Issue by hadizamani021** [jaraco/configparser#69]
**Description:**
I would like to propose the addition of a new feature to **ConfigParser** that enables the retrieval of configuration data as a nested dictionary.

**Suggested Functionality:**
Add a new method, say **to_dict()**, to the **ConfigParser** class that converts the parsed configuration into a nested dictionary.

**Example Usage:**

```
import configparser

config = configparser.ConfigParser()
config.read('example.ini')

nested_dict = config.to_dict()
print(nested_dict)

```
**Expected Output:**

```
{
    'general': {'name': 'John Doe', 'age': '30'},
    'address': {'street': '123 Main St', 'city': 'Anytown'},
    'contacts': {'email': 'john@example.com', 'phone': '555-1234'}
}

```

Thank you for considering this enhancement!

**Comment by jaraco** [comment]
Thanks for the suggestion.

Since configparser is a backport of the Python configparser module in the stdlib, this feature request should probably go there. Please consider re-posting your request there. When you do, it would also help to explain why this feature would be useful to you and why you think that other users would find the feature useful. I can imagine, but it strengthens the story to be explicit about the motivations and value of any additional behavior.

It may also help to provide some thoughts about a design - how would it work and what could go wrong? Also, why shouldn't this behavior exist as a standalone library or just an ad hoc implementation in downstream projects like yours?

You would also need to get a Core Python Developer sponsor to help guide the implementation. I _might_ be able to be that sponsor, but let's see if someone else has interest. Feel free to mention me in the re-file.
